name: Sync ChatGPT Notes to Obsidian (Windows)

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour (adjust if needed)
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync_notes:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch new notes from ChatGPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        shell: pwsh
        run: |
          # Ensure the chatgpt-notes directory exists
          if (!(Test-Path -Path "chatgpt-notes")) {
            New-Item -ItemType Directory -Path "chatgpt-notes"
          }

          # Call OpenAI API to fetch a new note
          $headers = @{
            "Authorization" = "Bearer $env:OPENAI_API_KEY"
            "Content-Type"  = "application/json"
          }

          $body = @{
           "model": "gpt-3.5-turbo"
            prompt    = "Write a short note about artificial intelligence."
            max_tokens = 200
          } | ConvertTo-Json -Depth 10

          $response = Invoke-RestMethod -Uri "https://api.openai.com/v1/completions" -Method Post -Headers $headers -Body $body

          # Extract text and save to a Markdown file
          $noteContent = $response.choices[0].text
          $timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm"
          $filePath = "chatgpt-notes\note-$timestamp.md"

          Set-Content -Path $filePath -Value $noteContent -Encoding UTF8

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        shell: pwsh
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "New ChatGPT note - $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
          git push https://$env:GH_PAT@github.com/sadjoo11/chatgpt-notes.git
