      - name: Fetch new notes from ChatGPT
        run: |
          mkdir -p chatgpt-notes  # Ensure the folder exists
          
          RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/completions" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-4",
              "prompt": "Write a short note about artificial intelligence.",
              "max_tokens": 200
            }' | jq -r '.choices[0].text')

          echo "$RESPONSE" > "chatgpt-notes/note-$(date +%Y-%m-%d_%H-%M).md"
