      - name: Fetch new notes from ChatGPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        shell: pwsh
        run: |
          # Ensure the chatgpt-notes directory exists
          if (!(Test-Path -Path "chatgpt-notes")) {
            New-Item -ItemType Directory -Path "chatgpt-notes"
          }

          # Set headers
          $headers = @{
            "Authorization" = "Bearer $env:OPENAI_API_KEY"
            "Content-Type"  = "application/json"
          }

          # Create the request body properly
          $body = @{
            model      = "gpt-3.5-turbo"
            prompt     = "Write a short note about artificial intelligence."
            max_tokens = 200
          } | ConvertTo-Json -Depth 10  # Convert hashtable to JSON

          # Call OpenAI API
          $response = Invoke-RestMethod -Uri "https://api.openai.com/v1/completions" -Method Post -Headers $headers -Body $body

          # Extract text and save to a Markdown file
          $noteContent = $response.choices[0].text
          $timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm"
          $filePath = "chatgpt-notes\note-$timestamp.md"

          Set-Content -Path $filePath -Value $noteContent -Encoding UTF8
