name: Sync ChatGPT Notes to Obsidian

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour (change if needed)
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync_notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch new notes from ChatGPT
        run: |
          mkdir -p chatgpt-notes  # Ensure the folder exists
          
          RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/completions" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-4",
              "prompt": "Write a short note about artificial intelligence.",
              "max_tokens": 200
            }' | jq -r '.choices[0].text')

          echo "$RESPONSE" > "chatgpt-notes/note-$(date +%Y-%m-%d_%H-%M).md"

           - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "New ChatGPT note - $(date)"
          git push https://$GH_PAT@github.com/sadjoo11/chatgpt-notes.git


